110 review and test voice cloning task
sensein/senselab pull request #132
Opened 2024-08-08 22:35 UTC by fabiocat93

PR to address the questions in https://github.com/sensein/senselab/issues/110

2024-08-08 22:40 UTC, fabiocat93 commented
hi @900miles, can you please review this? 
- I have added some proper doc introducing the task and fixed the docstring and made it in g-style
- adjusted the problems with `**kwargs`
- made the knnvc error messages more specific
- added tests with more than 2 elements
-

2024-08-14 00:23 UTC, 900miles reviewed
Looks great! Just a couple comments for clarity.

2024-08-14 00:23 UTC, 900miles commented on src/senselab/audio/tasks/voice_cloning/api.py
> +    """Clones voices from source audios to target audios using the given model.
I think we can be a little clearer on exactly what is happening. That this does a pairwise conversion from each audio in the source list onto the corresponding audio in the target list.

2024-08-14 00:23 UTC, 900miles commented on src/senselab/audio/tasks/voice_cloning/api.py
> +            Defaults to TorchModel(path_or_uri="bshall/knn-vc", revision="master").
We should specify in the documentation itself that as of now, only KNNVC is supported.

2024-08-14 14:11 UTC, fabiocat93 commented
@900miles thank you. i think i have fixed the last comments. feel free to approve the code if you think it's ready to be merged.

2024-08-14 23:02 UTC, 900miles requested changes
Thanks, just a couple more comments

2024-08-14 23:02 UTC, 900miles commented on tutorials/voice_cloning.ipynb
The colab link in this file points to the speech-to-text tutorial

2024-08-14 23:02 UTC, 900miles commented on src/senselab/audio/tasks/voice_cloning/api.py
> +    voices replaced by the voices from the corresponding source samples.
I'm pretty sure this is backwards. The resulting list contains the content of the source audio file with the voice changed to sound like the voice in the corresponding target audio file, right?

2024-08-15 21:44 UTC, fabiocat93 commented on src/senselab/audio/tasks/voice_cloning/api.py
> +    voices replaced by the voices from the corresponding source samples.
nice catch

2024-08-15 22:16 UTC, fabiocat93 commented
> Thanks, just a couple more comments

It should be ready for another review @900miles

2024-08-15 23:28 UTC, 900miles approved these changes
Looks great, thanks @fabiocat93!

2024-08-16 14:50 UTC, merged