Created SER tutorial
sensein/senselab pull request #201
Opened 2024-11-18 21:58 UTC by wilke0818

## Description
Creates a tutorial using Senselab for SER.

## Related Issue(s)
#197 

## Motivation and Context
We were lacking a tutorial using the functionality for audio classification, which currently has one specific implementation, speech emotion recognition, and so now novice users can better understand how to Senselab might be useful for this task.

## How Has This Been Tested?
Through Colab

2024-11-18 22:30 UTC, fabiocat93 commented
Thanks @wilke0818 for the tutorial! It’s helpful and does a good job of addressing real challenges that users might face. I like it, and I’m curious to see how actual users respond.

A few things are still missing to make this more complete:

1. **Senselab installation**: We should install `senselab` only when running in Colab. If the user is running elsewhere, we can assume they’ve already set it up. You can use a function like this:

```python
def is_colab():
    try:
        import google.colab
        return True
    except ImportError:
        return False

if is_colab():
    %pip install senselab
else:
    print("Not running on Colab. Skipping installation.")
```

2. **API for classification and SER**: Add an API for audio classification and speech emotion recognition (SER). For now, this API should call the Hugging Face-based function only if the model uses Hugging Face. If other types of models are used, raise a `NotImplementedError`. This will make this task more in line with the others in senselab and more easily maintainable. 

3. **Documentation for classification and SER**: Add documentation for these tasks. It should explain what the tasks are and link to the tutorial. You can use resources like this to get started: https://huggingface.co/tasks/audio-classification.

4. **This branch is out-of-date with the base branch**: Please, update the branch before requesting a new review.

Let me know if you need help with any of these points!

2024-11-20 02:37 UTC, fabiocat93 requested changes
Thanks @wilke0818 . I have commented some required changes

2024-12-23 15:26 UTC, fabiocat93 commented
hi, @wilke0818 ! Did you have any time to work on this?

2024-12-23 23:19 UTC, wilke0818 commented
Nope. Added the tutorial change that you gave (might not have updated). Need to refactor for the API per the other issue on this topic. It is unclear to me what you would want for documentation. The functionalities themselves are documented already and this tutorial provides the information about the task a user might need (it is pretty akin to the link you sent).

2025-01-09 23:00 UTC, fabiocat93 commented
> It is unclear to me what you would want for documentation. The functionalities themselves are documented already and this tutorial provides the information about the task a user might need (it is pretty akin to the link you sent).

Every task has a documentation page that explains what the task is, how it's commonly evaluated, what are the popular datasets and models. You can see the doc: https://sensein.group/senselab/senselab/audio/tasks/text_to_speech.html

2025-01-10 20:58 UTC, wilke0818 commented
I mean that makes sense but do we want this to be an SER task or a generic audio classification task (which is what the HuggingFace pipeline is) which doesn't have a specific task/dataset but where SER is just an example usage of the task?

2025-01-10 21:11 UTC, fabiocat93 commented
> I mean, that makes sense, but do we want this to be an SER task or a generic audio classification task (which is what the HuggingFace pipeline is) that doesn't have a specific task/dataset but where SER is just an example usage of the task?

Following https://github.com/sensein/senselab/issues/197, both. I would implement both a classification task (as HuggingFace has) and a SER task and would make it so that SER exploits the classification interfaces and employs some checks before and after (e.g., outputs should be emotion-related)

2025-01-16 20:48 UTC, wilke0818 commented
Need to write the documentation page for SER but otherwise this task (and the corresponding issue #197) are finished.

2025-01-22 17:44 UTC, wilke0818 commented
@fabiocat93 feel free to check and review the changes. Documentation pages have been added. SER tutorial should now be mostly complete (dimensional classification was removed since models for it don't really work with the audio-classification HF pipeline).

2025-01-22 20:12 UTC, fabiocat93 approved these changes
Looks good to me. @wilke0818: you may want to remove `src/senselab/audio/tasks/classification/speech_emotion_recognition/speech_emotion_recognition.py` if not required anymore.

2025-01-22 20:12 UTC, fabiocat93 commented on src/senselab/audio/tasks/classification/speech_emotion_recognition/speech_emotion_recognition.py
is this still required? @wilke0818

2025-02-04 01:15 UTC, fabiocat93 commented on src/senselab/audio/tasks/classification/speech_emotion_recognition/speech_emotion_recognition.py
Hey @wilke0818 , pinging you on this. I only need a yes/no. I can handle it from here. Thanks!

2025-02-04 16:50 UTC, wilke0818 commented on src/senselab/audio/tasks/classification/speech_emotion_recognition/speech_emotion_recognition.py
Yes it can be removed. I thought there might be one other requested change I needed to go back and do but if not then feel free.

2025-02-04 19:52 UTC, merged