Media Pipe Pose Estimation + Visualization
sensein/senselab pull request #203
Opened 2024-11-19 21:28 UTC by brukew

## Description
Implemented Media Pipe pose estimation. Given an image path, will return a PoseSkeleton object with landmarks of each individual in the image. 

## Related Issue(s)
https://github.com/orgs/sensein/projects/45/views/3?pane=issue&itemId=82951656&issue=sensein%7Csenselab%7C173

## Motivation and Context
This is the initial structure for pose estimation which is a valuable signal for behavior analysis. I will expand to more models and functionality, and with that, this will be more generalized.

## How Has This Been Tested?
I tested with different kinds of images and attempts to access invalid properties of the PoseSkeleton object. Unit tests for the new functions + also manually tested for proper visualization.

## Screenshots (if appropriate):

## Types of changes
Created PoseSkeleton object that contains pose information for individuals in an image. Currently supports MediaPipe pose estimation + visualization functionality.  

## Checklist:
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] My code follows the code style of this project.

2024-11-20 02:32 UTC, fabiocat93 commented
Thank you, @brukew, for the updates. I have a few suggestions and points to address based on our previous discussions:

1. **Reorganize Code Structure**  
   Please re-organize your code by separating **data structures** from **functionalities** (what we refer to as tasks in Senselab).  
   - The **skeleton** should be treated as a data structure. It should define the skeleton and optionally include utilities for visualization. Alternatively, visualization can be handled as a standalone task.  
   - **Pose estimation** should be a task (generating the skeleton as an output). All human pose estimation models (e.g., MediaPipe, AlphaPose) should conform to a consistent data structure.  
   - To encourage generalizability, I suggest integrating a second pose estimation tool, such as [YOLO](https://docs.ultralytics.com/tasks/pose/) due to its simplicity.

2. **Model Inclusion**  
   The current approach of including a model within the source code (e.g., `src/senselab/video/tasks/pose_estimation/models/pose_landmarker.task`) makes the package unnecessarily heavy. Instead, please ensure models are downloaded as needed. You can take inspiration from [this example](https://colab.research.google.com/github/googlesamples/mediapipe/blob/main/examples/pose_landmarker/python/%5BMediaPipe_Python_Tasks%5D_Pose_Landmarker.ipynb?hl=it).

3. **Documentation**  
   Please add a dedicated documentation page:  
   - Explain **human pose estimation** as a task, its purpose, and supported models.  
   - For instance, you can reference [this documentation](https://github.com/google-ai-edge/mediapipe/blob/master/docs/solutions/pose.md) for MediaPipe.  
   - Feel free to draw inspiration from the existing audio task documentation (though some sections are incomplete).

4. **Tutorial**  
   Create a Jupyter Notebook tutorial to demonstrate:  
   - How to use the interface.  
   - What functionalities are available.  
   Add this under a `video` folder in the `tutorial/` directory.

5. **Failing Tests**  
   I noticed two tests are failing:  
   - `test_valid_image_single_person`  
     - AssertionError: "Input and output image shapes should match."  
   - `test_visualization_single_person`  
     - ValueError: "Input image must contain three-channel BGR data."  
   Please double-check these tests to ensure they pass.

2024-11-20 02:37 UTC, fabiocat93 requested changes
@brukew, I have commented some required changes.

2024-11-20 16:39 UTC, brukew commented
Nice, thank you for the feedback @fabiocat93. I will address your comments and ask questions as I go.

2024-12-23 15:23 UTC, fabiocat93 commented
hi @brukew , did you have any time to work further on this?

2024-12-29 05:40 UTC, brukew commented
hey @fabiocat93, slowed down on development towards the end of the semester. I will continue this month.

2025-01-08 09:39 UTC, brukew commented
@fabiocat93 lmk what you think about having separate estimator classes for different models. also, I kept the landmark names as they are originally listed but wondering if I should homogenize them at all.

2025-01-09 23:15 UTC, fabiocat93 commented
> @fabiocat93 lmk what you think about having separate estimator classes for different models. also, I kept the landmark names as they are originally listed but wondering if I should homogenize them at all.

Good question. You can have multiple estimators, each being a child of the same abstract class and producing a skeleton following the same universal structure

2025-01-12 16:43 UTC, brukew commented
addressed model download by downloading models to video/tasks/pose_estimation/models upon use. Let me know if there is a better alternative to this that is more in line with senselab use.

2025-01-12 16:47 UTC, brukew commented
also wondering how I can ensure tutorial works (and cells are run in tutorial) if changes haven't been pushed to main branch @fabiocat93. should I wait until after?

2025-01-13 14:09 UTC, fabiocat93 commented
> addressed model download by downloading models to video/tasks/pose_estimation/models upon use. Let me know if there is a better alternative to this that is more in line with senselab use.

Good for now. But you raised a good point. We will need to implement a customizable cache folder for the package (of course with a default value)

2025-01-13 14:11 UTC, fabiocat93 commented
> also wondering how I can ensure tutorial works (and cells are run in tutorial) if changes haven't been pushed to main branch @fabiocat93. should I wait until after?


When testing the tutorial locally, you can install the package directly from a specific branch instead of relying on `pip install senselab`. This allows you to ensure the tutorial runs correctly with the latest changes before they are merged into the main branch

2025-01-16 23:17 UTC, fabiocat93 reviewed
@brukew : great work on this! I have a few suggestions and questions for consideration:

- I noticed the visualization method in the tutorial doesn't actually visualize the image but returns the array representation. Don’t you think it would make more sense for a visualization method (with the word visualize in the name) to display the image directly? Returning the array (and optionally saving it) could still be included as additional functionality.
- Is there a specific reason for having both IndividualPose and ImagePose? Would it make sense to simplify by treating IndividualPose as a special case of ImagePose where there’s only one subject? It might reduce redundancy and improve maintainability.
- I noticed there’s no mapping of the skeletons into a more general senseLab skeleton yet, and the visualization method is method-specific rather than generic for senselab. Was there a challenge in unifying this? Having two different skeletons and implementations feels less maintainable. Is there a particular reason for this approach?

Let me know if you’d like to discuss any of these points. I’m happy to help! Also, let me know if you prefer to fix the minor questions and merge and keep the rest of the changes for a future PR or if you want to keep it more ordered and work on this until everything is ready.

2025-01-16 23:18 UTC, fabiocat93 commented
A quick note for the entire group about installation: the number of dependencies, especially for video, makes installation quite heavy. Moving forward, we might want to split the package into modules like senselab[audio], senselab[video], and senselab[text]. This would simplify installation based on the user’s needs

2025-01-17 09:14 UTC, brukew commented
Hey @fabiocat93, thanks for the comments - I will make all changes before merging. Here are my thoughts:

1. Yes, that makes sense. I will do that.

2. I think it gives us greater power for anything we want to do later. For example, if a video has different people over time, we could combine face analysis and pose estimation to aggregate the poses of an individual across frames which would be easier with IndividualPose object (with tweaks). It's also just intuitive to have a separate object for each individual detected. I could take it out for now though.

3. I can do this. My thinking was that users could have access to whatever the given model output is and they can work with it how they want to, but I figure that defeats the point of having these in Senselab. So I guess I'll make a Senselab keypoint mapping and attempt to not lose any information across the models - so it includes all possible key points across models. What do you think about that?

2025-01-17 14:32 UTC, fabiocat93 commented
> I think it gives us greater power for anything we want to do later. For example, if a video has different people over time, we could combine face analysis and pose estimation to aggregate the poses of an individual across frames which would be easier with IndividualPose object (with tweaks). It's also just intuitive to have a separate object for each individual detected. I could take it out for now though.

You convinced me with this. but how about always returning back an ImagePose object (which may include as many IndividualPose objects as the number of people detected?)

> I can do this. My thinking was that users could have access to whatever the given model output is and they can work with it how they want to, but I figure that defeats the point of having these in Senselab. So I guess I'll make a Senselab keypoint mapping and attempt to not lose any information across the models - so it includes all possible key points across models. What do you think about that?

Sounds great! And please let me know if you need or want to brainstorm it further before implementing it.

2025-01-21 21:55 UTC, brukew commented
@fabiocat93 Addressed the visualization and keypoint mapping comments. The tests kept failing on Git Hub when a plot was created - my workaround was adding a bool parameter for plotting but let me know if there is another way that you want me to handle that.

2025-01-22 20:30 UTC, fabiocat93 approved these changes
Looks good to me. Nice job @brukew ! Looking forward to seeing more models integrated and some cools analyses based on this!!

2025-01-22 20:31 UTC, merged